version: '3'

services:

  reviews:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'database'
    ports:
      - '3333:3002'

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
